image: alpine:latest

stages:
  - coordinate

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"  # Full history

before_script:
  - apk add --no-cache bash git curl jq coreutils

swarm-coordinator:
  stage: coordinate
  script:
    - chmod +x ./swarm-coordinator.sh
    - ./swarm-coordinator.sh
  
  after_script:
    - |
      if [ -f .swarm/manifest.json ]; then
        echo "Current swarm manifest:"
        cat .swarm/manifest.json | jq . || cat .swarm/manifest.json
      fi
  
  rules:
    # Run on push to main/master
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      when: always
    
    # Run on schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    
    # Manual trigger
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# Schedule configuration (configure via GitLab UI: CI/CD -> Schedules)
# Recommended: "0 */6 * * *" (every 6 hours)
